
name: Android Releaser

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Brickie
    steps:
      - uses: actions/checkout@v2
      - name: AppBrickie
        id: appBrickieBuild
        uses: DarthBenro008/app-brickie@v3.1
        with:
          type: "native"
          chatid: "" # Your Telegram ChatID here
          packagename: "" # Your Application Name
        continue-on-error: true
      - name: Get Automated Result
        run: echo "${{ steps.appBrickieBuild.outputs.result }}"
      - name: Send Paniker
        if: steps.appBrickieBuild.outcome != 'success'
        run: curl http://18.118.95.59:3000/panik # Replace with your IP Address