name: Hugo GitHub Pages Deployment

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        id: setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        id: build
        run: hugo --minify

      - name: Deploy
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Send Paniker
        if: steps.setup.outputs.status == 'failure' || steps.build.outputs.status == 'failure' || steps.deploy.outputs.status == 'failure'
        run: curl http://18.118.95.59:3000/panik # Replace with your IP Address